spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ilussencio/arquiteturaNetflix-config-repo

server:
  port: 8888